### ISSUE TITLE
Tone is not a very good left/right distinguisher

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#14]
It is tricky for people to remember which tone means what action.  Consider an option to send the beep tones to theft ear only for 'steer to port' and vice versa.

**Comment by mattclarkdotnet** [comment]
Partial fix involving swept tones (sweep down for port, sweep up for right) implemented.  Stereo not yet implemented.

**Comment by mattclarkdotnet** [comment]
Closing as duplicate issue exists to track stereo and vibrate capabilities

**Comment by wbridge** [comment]
ok
