### ISSUE TITLE
lack of defined interaction model may result in early users being disappointed

### ISSUE THREAD

**Issue by wbridge** [mattclarkdotnet/viscompass#17]
eg wired or wireless
how smartphone positioned 
expectations of users
conditions which it is appropriate for
feedback from early users

**Comment by mattclarkdotnet** [comment]
Also consider the right amount of ambient/signal audio feed - is it OK for the helm to be isolated by in-ear phones?

**Comment by mattclarkdotnet** [comment]
Suggest we avoid making the visual display usable by anyone other than fully sighted crew for now
