### ISSUE TITLE
name must be changed to VIS Compass

### ISSUE THREAD

**Issue by wbridge** [mattclarkdotnet/viscompass#18]
so long as name in appstore and any userdocs are changed - ok

**Comment by mattclarkdotnet** [comment]
Done on github, in the code and in the Xcode project.

**Comment by wbridge** [comment]
Great thanks

See also the distance I’ve put between VISCompass and any BBC inspired yacht racing software (ie lots of references to cruising / passage making etc)... in the latest readme

W
