### ISSUE TITLE
Initial prime use of VISCompass screen interface by sighted skipper may still require bold buttons due to gloves/clothing/boat movement

### ISSUE THREAD

**Issue by wbridge** [mattclarkdotnet/viscompass#19]

**Comment by mattclarkdotnet** [comment]
Layout much improved in recent builds

**Comment by wbridge** [comment]
Agreed. But closeness on the screen of the set and unset buttons still requires care/delicacy/ungloved hands

**Comment by wbridge** [comment]
Looks like some great work on this tonight Matt – far more rewarding than accepting that invite to the star wars premiere!

Speak soon 

Wx
