### ISSUE TITLE
Code triggered by timers is not thread safe

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#22]
Well, maybe it is and maybe it isn't, but I don't know enough to say for sure.  Specifically ViewController.UpdateUI and ViewController.beepMaybe are called from timers and also from code run by user input triggers.  If Swift/Cocoa/iOS handles this safely then great, but it needs investigation.

**Comment by mattclarkdotnet** [comment]
Code now looks safe as all timers are destroyed on entry to the function and recreated as needed.

**Comment by wbridge** [comment]
lost me in the jargon  here!...but it reminds me I need to test functionality over long period - 3-4 hours
