### ISSUE TITLE
Smoothing window is not adjustable by user

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#23]
Different sailing conditions might require different smoothing windows for the heading other than the default 10 seconds.  Make the setting available and give it a name meaningful to users.

**Comment by wbridge** [comment]
Do you mean 10 degrees?

**Comment by mattclarkdotnet** [comment]
Fixed by adjustable convergence window QQ-SS

**Comment by wbridge** [comment]
I look forward to trying it out . As I said , variability needed to cope with varying vessel characteristics ( and perhaps we may find , by different helming techniques/folk)
