### ISSUE TITLE
Gamma of heading history is not adjustable by user

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#24]
The significance of previous samples of heading data is discounted by a t^2 function, but this is something that might need to be changed to suit sailing conditions.  Make this setting available under a sensible user-meaningful name.

**Comment by mattclarkdotnet** [comment]
Fixed - convergence time now adjustable from 1-10 seconds by segmented UI control offering QQ (1s) Q (2s), M (3.5s), S (6s), SS (10s).

**Comment by wbridge** [comment]
great
