### ISSUE TITLE
Although wireless/bluetooth earpieces are ideal for on board mobility , they can be tricky to use/adjust. For example , their volume controls , stop/start etc controls are often on the earpiece casing , just where you grab it when a gust of wind tries to blow it away!

### ISSUE THREAD

**Issue by wbridge** [mattclarkdotnet/viscompass#30]

**Comment by mattclarkdotnet** [comment]
Given the phone needs to be held in place when in use for sailing it'd be difficult to recommend using the phone's audio controls.  Are there specific bluetooth devices that are better than others?

**Comment by wbridge** [comment]
Actually the currenr tak tik instrument doesn't have a vol control.  And many wired earphones have a neat in- lead vol control

Will Bridge
07802 306006
mail@willbridge.com or wandj@willbridge.com
