### ISSUE TITLE
The UI layout is poorly done and doesn't work across devices

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#4]
http://www.raywenderlich.com/113768/adaptive-layout-tutorial-in-ios-9-getting-started

**Comment by mattclarkdotnet** [comment]
The controls are too close to the edge of the screen
The controls are too small
The controls move about
Basically someone who understands iOS UI layout needs to sort it out

**Comment by mattclarkdotnet** [comment]
I'm going to close this as 'good enough' now.  The UI is still a bit amateur but it does now work properly across devices and size classes and isn't obviously broken.

**Comment by wbridge** [comment]
Great – Only remaining issue may be size of the course setting on/off slider. It’s the most commonly used button on the interface , and needs to be both clearly off or on (which it now is – at least to reasonably well sighted folk) .........and large/supereasy to operate (which it isn’t quite – though we must avoid this control being susceptible to being inadvertently operated)

**Comment by wbridge** [comment]
Putting the two available adjustments together and in blue at the bottom of the main screen looks brilliant and works well . 

We need to explain to ourselves and then to users what the two scales “do” , and (rather like explaining the tackswipe) we need to provide instructions for using them somewhere

My explanation to myself runs something like

The “Tolerance” control  sets the amount of off course angle (say plus or minus 5 degrees)  at which VISCompass’s correction beeps start sounding

The “Sensitivity” control (if we label it – probably should) sets how quickly VISCompass decides you are more than the tolerance angle (say 5 degrees) off course , so if set to “ss” , it wont beep at all if say a passing wave just momentarily shoves the boat beyond 5 degrees

But I’m not sure I’m even correct about the sensitivity definition!!
