### ISSUE TITLE
The app doesn't have a launch screen

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#5]

**Comment by mattclarkdotnet** [comment]
Created a launch screen that is just the app icon.

**Comment by wbridge** [comment]
I suppose the launch screen could also have some basic instructions and credits on it?... not a great solution 

Also the little app enrolment blurb currently refers to the auspices being the  Blind Sailing Trust. It’s actually the SAD- “Sporting Activities for the Disabled Trust”... but this is such a mouthful I’d be inclined to just erase that half sentence (especially as some VI’s aren’t keen on being lumped together with “the disabled” or even “the blind”)
