### ISSUE TITLE
Tacking involves too much fiddling with the target heading controls

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#6]
Allow a user to tell the app to specify a change of course of a fixed amount (e.g. 100 degrees) to port or starboard to help with tacking.

**Comment by mattclarkdotnet** [comment]
Fixed through 'swipe to tack' in version 1.0 build 2

**Comment by wbridge** [comment]
Great functionality , but given the uncertainty of whether swipes are successfully registered by the phone  (and the risks associated with inputting a double swipe) , it would be great if there could be visual and audio confirmation of a tackswipe having been accomplished 

The tackswipe function is one VISCompass feature which is not self explanatory – you’d probably never find it from just playing with the main screen. I guess it will need to be explained in an “advanced” or an “instructions” page – much as we were trying to avoid too much of that.

So what is out thinking about both such a page , and  about revealing other variable parameters (no no , not yet!) , and also about a credits/contacts/context/feedback page
