### ISSUE TITLE
Low pitched sound is not audible enough

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#7]
The 'low pitched' beep sound is almost inaudible through phone speakers, and easily masked by boat noise when wearing headphones.  Also pitch alone isn't very easy to learn as a L/R indicator.

We should make the beep sounds closer in pitch (though still an octave apart) and also make them very different timbres.

**Comment by mattclarkdotnet** [comment]
Fixed with new sounds, but I still think there's something wrong with the intuitive meaning of high vs low pitch.  High for me intuitively means turn right/starboard.  The older devices use high pitches for turn left/port.  Maybe now is the time to change over?

**Comment by wbridge** [comment]
Yes I agree – lets do that change

W
