### ISSUE TITLE
Course correction display is ambiguous

### ISSUE THREAD

**Issue by mattclarkdotnet** [mattclarkdotnet/viscompass#9]
Sighted crew cannot easily tell just by looking at the device display whether the desired correction is to steer starboard or port.  Colour is simply confusing - does it indicate the course to steer or the angle of error?  A better visual is needed.  Consider instructing that the phone is oriented 'top to bow' and giving arrows or such like on screen.

**Comment by mattclarkdotnet** [comment]
Fixed by large red/green arrows pointing the correction direction (assuming the top of the phone is toward the bow)

**Comment by wbridge** [comment]
sounds good . I'll need to put that (rather obvious admittedly) orientation point in the readme
